---

- name: Create MEF EVPL Service
  hosts: "3903x_4"
  vars:
      stag: 200
      ctag: 20
      uniPort: 2
      nniPort: 3
      mepid: 2
  connection: netconf
  gather_facts: false
  tasks:
      - name: "TASK1: Create Flow Domain"
        netconf_config:
            content: "{{ lookup('template', 'templates/fdsVlanCreate.j2') }}"
      - name: "Task2: Create NNI Classifier"
        netconf_config:
            content: "{{ lookup('template', 'templates/classifiersCreate.j2') }}"
      - name: "Task3: Create Flow Point"
        netconf_config:
            content: "{{ lookup('template', 'templates/fpsCreate.j2') }}"
      - name: "Task4: Create Flow Domain(VPLS)/VS/VC"
        netconf_config:
            content: "{{ lookup('template', 'templates/fdsVplsCreate.j2') }}"
      - name: "Task5: Create VPLS/UNI Classifier"
        netconf_config:
            content: "{{ lookup('template', 'templates/classifiersVplsCreate.j2') }}"
      - name: "Task6: Connect VS to VC"
        netconf_config:
            content: "{{ lookup('template', 'templates/fpsVplsCreate.j2') }}"
      - name: "Task7: FP - Connect VS to Uni"
        netconf_config:
            content: "{{ lookup('template', 'templates/fpsVplsCreateUni.j2') }}"
      - name: "Task8: Service CFM provisioning"
        netconf_config:
            content: "{{ lookup('template', 'templates/serviceCfm.j2') }}"
      - name: "Task9: Enable Global CFM Service"
        netconf_config:
            content: "{{ lookup('template', 'templates/globalCfmEnable.j2') }}"
