---

- name: "Create Single VNF"
  hosts: "home3906"
  vars:
      vnfName: "vyos"
      numCpu: 2
      mem: 4096
      netIfs:
          - ifname: "mgmt-eth0"
            iftype: "default" 
            interface: "default"
          - ifname: "lan-eth1"
            iftype: "vhost" 
            interface: "vnet-0"
          - ifname: "wan-eth2"
            iftype: "vhost" 
            interface: "vnet-1"
      image_path: ftp://192.168.2.3/vyos.qcow2
      image_size: 365
      ftp_username: "pi"
      ftp_password: "Ciena123!"
      createUntaggedClassifier: true
      taggedClassifiers:
          - 100
          - 200
          - 300
  connection: netconf
  gather_facts: false
  tasks:
      - name: "Create VNF"
        netconf_config:
            content: "{{ lookup('template', 'templates/sfsCreate.j2') }}"    
      - name: "Start VNF"
        netconf_config:
            content: "{{ lookup('template', 'templates/sfsStart.j2') }}"
      - name: "Create Classifiers"
        netconf_config:
            content: "{{ lookup('template', 'templates/dnfviClassCreate.j2') }}"
